---
- hosts: install_pong
  become: yes
  tasks:
     - name: "download pong"
       get_url:
          url: https://github.com/kurehajime/pong-command/releases/download/v2.0.3/linux_386.zip
          dest: /tmp/linux_386.zip
     - name: "unarchive pong"
       unarchive:
          src: /tmp/linux_386.zip
          dest: ~/../../bin
          remote_src: yes
  


 